#!/usr/bin/env python3
"""Thumbnails and page facts for the Radio Path Maps catalogue.

Reads every map maps-data.js catalogues (its FILE_PATH, rebuilt here from
MAP_CATALOG + REGION_DIR), renders page 1 of each to a small WebP under
maps/thumbs/<region>/, and rewrites the generated FILE_META block in
maps-data.js with what the file itself says: size on disk, pages, paper size,
orientation, the date the PDF was made, and whether it is a scan.

    python3 tools/build_map_thumbs.py            # write thumbs + FILE_META
    python3 tools/build_map_thumbs.py --check    # exit 1 if anything is stale

Needs poppler-utils (pdftoppm, pdfinfo) and Pillow. Run it after adding,
replacing or removing a map; the catalogue shows a placeholder for a map with
no thumbnail, so a missed run is visible rather than broken.
"""
import argparse
import io
import json
import os
import re
import subprocess
import sys
import tempfile
from datetime import datetime, timezone

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, 'maps-data.js')
THUMB_DIR = 'maps/thumbs'
LONG_EDGE = 288          # px — twice the catalogue's largest display box
QUALITY = 58

BEGIN = '  // ── FILE_META — generated by tools/build_map_thumbs.py; do not edit by hand ──'
END = '  // ── end FILE_META ──'

# ISO A-series short sides in mm. A page within 3% of one is called by name.
A_SERIES = {'A0': 841, 'A1': 594, 'A2': 420, 'A3': 297, 'A4': 210, 'A5': 148}
SCANNERS = re.compile(r'apeosport|scan|xerox|ricoh|canon ir|kyocera|konica', re.I)


def catalogue():
    """FILE_PATH, rebuilt from the catalogue in maps-data.js via node."""
    js = (
        "global.window={};require(process.argv[1]);"
        "process.stdout.write(JSON.stringify(window.MegaNetMaps.FILE_PATH))"
    )
    out = subprocess.run(['node', '-e', js, DATA], check=True, capture_output=True, text=True)
    return json.loads(out.stdout)


def pdfinfo(path):
    out = subprocess.run(['pdfinfo', path], check=True, capture_output=True, text=True).stdout
    info = {}
    for line in out.splitlines():
        k, _, v = line.partition(':')
        info[k.strip()] = v.strip()
    return info


def pdf_date(s):
    # pdfinfo prints e.g. "Wed Feb 28 04:43:41 2018 UTC"
    if not s:
        return None
    for fmt in ('%a %b %d %H:%M:%S %Y %Z', '%a %b %d %H:%M:%S %Y'):
        try:
            return datetime.strptime(re.sub(r'\s+', ' ', s), fmt).replace(tzinfo=timezone.utc).date().isoformat()
        except ValueError:
            pass
    return None


def paper(w_pt, h_pt):
    short_mm = min(w_pt, h_pt) * 25.4 / 72
    for name, mm in A_SERIES.items():
        if abs(short_mm - mm) / mm < 0.03:
            return name
    return None


def render(path):
    """Page 1 as a PIL image, rotation applied, long edge LONG_EDGE."""
    if not path.lower().endswith('.pdf'):
        img = Image.open(path)
        img.load()
        return img.convert('RGB')
    with tempfile.TemporaryDirectory() as tmp:
        stem = os.path.join(tmp, 'p')
        subprocess.run(['pdftoppm', '-f', '1', '-l', '1', '-singlefile', '-png',
                        '-scale-to', str(LONG_EDGE * 2), path, stem], check=True)
        img = Image.open(stem + '.png')
        img.load()
        return img.convert('RGB')


def webp_bytes(img):
    img = img.copy()
    img.thumbnail((LONG_EDGE, LONG_EDGE), Image.LANCZOS)
    buf = io.BytesIO()
    img.save(buf, 'WEBP', quality=QUALITY, method=6)
    return buf.getvalue(), img.size


def meta_for(name, rel):
    path = os.path.join(ROOT, rel)
    m = {'bytes': os.path.getsize(path)}
    img = render(path)
    w, h = img.size
    if rel.lower().endswith('.pdf'):
        info = pdfinfo(path)
        m['pages'] = int(info.get('Pages', '1') or 1)
        size = re.match(r'([\d.]+) x ([\d.]+)', info.get('Page size', ''))
        if size:
            pw, ph = float(size.group(1)), float(size.group(2))
            m['paper'] = paper(pw, ph)
            if int(info.get('Page rot', '0') or 0) % 180:
                pw, ph = ph, pw
            # The page's own proportions, not the rounded pixels — but only
            # when they agree with the render on which way up the page is.
            if (pw > ph) == (w > h):
                w, h = pw, ph
        made = pdf_date(info.get('CreationDate'))
        edited = pdf_date(info.get('ModDate'))
        if made:
            m['made'] = made
        if edited and edited != made:
            m['edited'] = edited
        if SCANNERS.search(info.get('Producer', '') + ' ' + info.get('Creator', '')):
            m['scanned'] = True
    else:
        m['pages'] = 1
    # Orientation with /Rotate applied — the MediaBox alone says portrait for
    # most of the landscape A3 sheets.
    m['orient'] = 'landscape' if w > h else 'portrait'
    m['aspect'] = round(w / h, 4)
    stem = os.path.splitext(os.path.basename(rel))[0]
    region_dir = os.path.basename(os.path.dirname(rel))
    m['thumb'] = f'{THUMB_DIR}/{region_dir}/{stem}.webp'
    data, (tw, th) = webp_bytes(img)
    m['tw'], m['th'] = tw, th
    return m, data


def block(meta):
    lines = [BEGIN,
             '  // One entry per catalogued map: what the file itself says. `aspect` is the',
             '  // first page\'s width / height with its rotation applied; `thumb` is a',
             f'  // {LONG_EDGE}px WebP of that page; `made` / `edited` are the PDF\'s own dates.',
             '  const FILE_META = {']
    for name in sorted(meta, key=str.lower):
        lines.append(f'    {json.dumps(name)}: {json.dumps(meta[name], separators=(", ", ": "))},')
    lines.append('  };')
    lines.append(END)
    return '\n'.join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--check', action='store_true', help='report stale output, write nothing')
    args = ap.parse_args()

    paths = catalogue()
    stems = {}
    for name, rel in paths.items():
        key = os.path.join(os.path.dirname(rel), os.path.splitext(os.path.basename(rel))[0])
        if key in stems:
            sys.exit(f'two maps would share a thumbnail: {stems[key]!r} and {name!r}')
        stems[key] = name

    meta, stale = {}, []
    for name, rel in sorted(paths.items()):
        if not os.path.exists(os.path.join(ROOT, rel)):
            sys.exit(f'catalogued but missing on disk: {rel}')
        m, data = meta_for(name, rel)
        meta[name] = m
        out = os.path.join(ROOT, m['thumb'])
        # --check asks only whether a thumbnail exists: another machine's
        # poppler or libwebp renders different bytes from the same page.
        old = open(out, 'rb').read() if os.path.exists(out) else None
        if old is None or (not args.check and old != data):
            stale.append(m['thumb'])
            if not args.check:
                os.makedirs(os.path.dirname(out), exist_ok=True)
                with open(out, 'wb') as fh:
                    fh.write(data)

    src = open(DATA, encoding='utf-8').read()
    new_block = block(meta)
    if BEGIN in src:
        start = src.index(BEGIN)
        end = src.index(END, start) + len(END)
        new_src = src[:start] + new_block + src[end:]
    else:
        anchor = '  global.MegaNetMaps = {'
        new_src = src.replace(anchor, new_block + '\n\n' + anchor, 1)
    if new_src != src:
        stale.append('maps-data.js FILE_META')
        if not args.check:
            with open(DATA, 'w', encoding='utf-8') as fh:
                fh.write(new_src)

    # Thumbnails nobody catalogues any more.
    wanted = {os.path.normpath(os.path.join(ROOT, m['thumb'])) for m in meta.values()}
    for dirpath, _, files in os.walk(os.path.join(ROOT, THUMB_DIR)):
        for f in files:
            p = os.path.normpath(os.path.join(dirpath, f))
            if p not in wanted:
                stale.append(os.path.relpath(p, ROOT) + ' (orphan)')
                if not args.check:
                    os.remove(p)

    total = sum(os.path.getsize(os.path.join(ROOT, m['thumb']))
                for m in meta.values() if os.path.exists(os.path.join(ROOT, m['thumb'])))
    if args.check:
        if stale:
            print('stale:\n  ' + '\n  '.join(stale))
            sys.exit(1)
        print(f'{len(meta)} maps, thumbnails and FILE_META current ({total // 1024} KB)')
    else:
        print(f'{len(meta)} maps; {len(stale)} written or removed; thumbnails {total // 1024} KB')


if __name__ == '__main__':
    main()
