#!/usr/bin/env python3
"""MegaNet agent — answer questions about the station network with the Claude API.

This is a reference implementation of an *agentic* Claude API loop that uses
**code execution with tools** (programmatic tool calling): Claude runs Python in
an Anthropic-hosted sandbox and, from inside that sandbox, calls a custom
`query_stations` tool that reads the local ``stations.json``. Because the
dataset is large (3,000+ stations), this keeps the raw records out of the model
context — Claude filters and aggregates in code and only the answer comes back.

--------------------------------------------------------------------------------
The container_id fix
--------------------------------------------------------------------------------
When a custom tool is invoked from *inside* the code-execution sandbox, that
tool-use is tied to a sandbox **container**. The naive loop sends the tool
results back on the next request without referencing the container, and the API
rejects it:

    HTTP 400: container_id is required when there are pending tool uses
    generated by code execution with tools.

The fix is to capture ``response.container.id`` and pass it back as the
``container=`` argument on every follow-up request so the API resumes the same
sandbox. See ``_run_turn`` below (the ``if container_id:`` branch).

--------------------------------------------------------------------------------
Usage
--------------------------------------------------------------------------------
    export ANTHROPIC_API_KEY=sk-ant-...
    python3 tools/meganet_agent.py "How many repeaters are in the Burdekin River basin?"
    python3 tools/meganet_agent.py --verbose "List field stations in Townsville City LGA"

Requires: ``pip install anthropic`` (Python 3.9+). The API key is read from the
``ANTHROPIC_API_KEY`` environment variable and is never written to disk.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

try:
    import anthropic
except ImportError:
    sys.exit("This tool requires the Anthropic SDK. Install it with: pip install anthropic")

# The code-execution tool version that supports programmatic tool calling
# (custom tools callable from inside the sandbox). Opus 4.5+ / Sonnet 4.5+.
CODE_EXECUTION_TOOL = {"type": "code_execution_20260120", "name": "code_execution"}
DEFAULT_MODEL = "claude-opus-4-8"
DEFAULT_STATIONS = Path(__file__).resolve().parent.parent / "stations.json"

SYSTEM_PROMPT = (
    "You are the MegaNet network analyst. MegaNet is a Bureau of Meteorology radio "
    "and satcom telemetry network. Answer questions about the station network using "
    "the query_stations tool for the ground truth — never guess station data. Prefer "
    "writing Python in the code execution sandbox and calling query_stations from "
    "there to filter and aggregate, so you only bring the answer back into context. "
    "Be concise and lead with the answer."
)


def _station_summary(s: dict) -> dict:
    """A compact view of a station record (keeps tool payloads small)."""
    return {
        "id": s.get("id"),
        "name": s.get("name"),
        "station_number": s.get("station_number"),
        "lat": s.get("lat"),
        "lon": s.get("lon"),
        "basin": s.get("basin"),
        "lga": s.get("lga"),
        "roles": s.get("roles", []),
        "radio_network_ids": s.get("radio_network_ids", []),
        "catchment_ids": s.get("catchment_ids", []),
        "alert_ids": s.get("alert_ids", {}),
        "satcom_enabled": bool(s.get("satcom", {}).get("enabled")),
    }


def make_query_stations_tool(stations: list[dict]):
    """Return the tool definition and its executor, closing over the data.

    ``allowed_callers`` is what makes this tool callable from inside the
    code-execution sandbox (programmatic tool calling).
    """
    tool_def = {
        "name": "query_stations",
        "description": (
            "Query the MegaNet station database. Combine any filters (AND). "
            "Returns {'count': N, 'stations': [...]}; {'count': N} when count_only; "
            "or {'groups': [{'value', 'count'}, ...]} (descending) when group_by is set "
            "— use group_by to rank basins/LGAs etc. in a single call instead of guessing. "
            "Field hints: roles are 'field' | 'repeater' | 'base'; basin is a river "
            "basin name e.g. 'Burdekin River'; lga is a local government area e.g. "
            "'Townsville City'. Matching is case-insensitive substring for name/basin/lga."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "name_contains": {"type": "string", "description": "Substring of station name."},
                "basin": {"type": "string", "description": "River basin name (substring)."},
                "lga": {"type": "string", "description": "Local government area (substring)."},
                "role": {"type": "string", "enum": ["field", "repeater", "base"]},
                "satcom": {"type": "boolean", "description": "Only satcom-enabled stations."},
                "radio_network_id": {"type": "string"},
                "catchment_id": {"type": "string"},
                "alert_id": {"type": "integer", "description": "Match a station carrying this ALERT id."},
                "group_by": {
                    "type": "string",
                    "enum": ["basin", "lga", "role", "radio_network_id", "catchment_id"],
                    "description": "Return counts per distinct value of this field (after filters).",
                },
                "count_only": {"type": "boolean", "default": False},
                "limit": {"type": "integer", "default": 50,
                          "description": "Max stations (or groups) returned (1-500)."},
            },
            "additionalProperties": False,
        },
        # Callable from within the code-execution sandbox:
        "allowed_callers": ["code_execution_20260120"],
    }

    def _run(inp: dict) -> str:
        def norm(x):
            return str(x).lower()

        matches = []
        for s in stations:
            if (nc := inp.get("name_contains")) and norm(nc) not in norm(s.get("name", "")):
                continue
            if (b := inp.get("basin")) and norm(b) not in norm(s.get("basin", "")):
                continue
            if (lga := inp.get("lga")) and norm(lga) not in norm(s.get("lga", "")):
                continue
            if (role := inp.get("role")) and role not in s.get("roles", []):
                continue
            if inp.get("satcom") is True and not s.get("satcom", {}).get("enabled"):
                continue
            if (rn := inp.get("radio_network_id")) and rn not in s.get("radio_network_ids", []):
                continue
            if (cc := inp.get("catchment_id")) and cc not in s.get("catchment_ids", []):
                continue
            if (aid := inp.get("alert_id")) is not None:
                ids = set(s.get("alert_ids", {}).values())
                ids |= {sen.get("alert_id") for sen in s.get("sensors", [])}
                if aid not in ids:
                    continue
            matches.append(s)

        limit = max(1, min(int(inp.get("limit", 50)), 500))

        if gb := inp.get("group_by"):
            field = "roles" if gb == "role" else gb
            counts: dict = {}
            for s in matches:
                val = s.get(field)
                vals = val if isinstance(val, list) else [val]
                for v in vals:
                    if v not in (None, ""):
                        counts[v] = counts.get(v, 0) + 1
            groups = sorted(counts.items(), key=lambda kv: kv[1], reverse=True)[:limit]
            return json.dumps({"group_by": gb, "count": len(matches),
                               "groups": [{"value": v, "count": n} for v, n in groups]})

        if inp.get("count_only"):
            return json.dumps({"count": len(matches)})
        return json.dumps(
            {"count": len(matches), "stations": [_station_summary(s) for s in matches[:limit]]}
        )

    return tool_def, _run


def _run_turn(client, *, model, max_tokens, tools, messages, container_id):
    kwargs = dict(model=model, max_tokens=max_tokens, tools=tools, messages=messages,
                  system=SYSTEM_PROMPT)
    # ---- THE FIX: resume the same code-execution sandbox on follow-up turns ----
    if container_id:
        kwargs["container"] = container_id
    return client.messages.create(**kwargs)


def run_agent(question: str, *, stations_path: Path, model: str, max_tokens: int,
              max_turns: int, verbose: bool) -> str:
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        sys.exit("Set ANTHROPIC_API_KEY in the environment before running.")

    data = json.loads(Path(stations_path).read_text())
    stations = data["stations"] if isinstance(data, dict) else data
    query_def, run_query = make_query_stations_tool(stations)
    tools = [CODE_EXECUTION_TOOL, query_def]

    executors = {"query_stations": run_query}
    messages = [{"role": "user", "content": question}]
    container_id = None
    client = anthropic.Anthropic(api_key=api_key)

    for turn in range(1, max_turns + 1):
        resp = _run_turn(client, model=model, max_tokens=max_tokens, tools=tools,
                         messages=messages, container_id=container_id)
        # Remember the sandbox so the next request can resume it.
        if getattr(resp, "container", None):
            container_id = resp.container.id
        if verbose:
            print(f"[turn {turn}] stop_reason={resp.stop_reason} container={container_id}",
                  file=sys.stderr)

        messages.append({"role": "assistant", "content": resp.content})

        if resp.stop_reason in ("end_turn", "stop_sequence"):
            return "".join(b.text for b in resp.content if b.type == "text").strip()

        # Server-side tool loop hit its internal cap; re-send to let it resume.
        if resp.stop_reason == "pause_turn":
            continue

        # Programmatic / direct tool calls: reply with ONLY tool_result blocks.
        tool_results = []
        for block in resp.content:
            if block.type == "tool_use":
                try:
                    content = executors[block.name](block.input)
                    is_error = False
                except Exception as exc:  # surface tool failures back to the model
                    content, is_error = f"tool error: {exc}", True
                tool_results.append({
                    "type": "tool_result",
                    "tool_use_id": block.id,
                    "content": content,
                    "is_error": is_error,
                })
        if not tool_results:
            break
        messages.append({"role": "user", "content": tool_results})

    return "(agent stopped without a final answer — try raising --max-turns)"


def main(argv=None):
    parser = argparse.ArgumentParser(description="Ask the Claude-powered MegaNet agent about the station network.")
    parser.add_argument("question", nargs="?", help="Natural-language question about the network.")
    parser.add_argument("--model", default=DEFAULT_MODEL, help=f"Claude model id (default: {DEFAULT_MODEL}).")
    parser.add_argument("--max-tokens", type=int, default=8000)
    parser.add_argument("--max-turns", type=int, default=12, help="Safety cap on agentic loop iterations.")
    parser.add_argument("--stations", type=Path, default=DEFAULT_STATIONS, help="Path to stations.json.")
    parser.add_argument("--verbose", action="store_true", help="Print a per-turn trace to stderr.")
    args = parser.parse_args(argv)

    question = args.question or sys.stdin.read().strip()
    if not question:
        parser.error("provide a question as an argument or on stdin")

    answer = run_agent(
        question,
        stations_path=args.stations,
        model=args.model,
        max_tokens=args.max_tokens,
        max_turns=args.max_turns,
        verbose=args.verbose,
    )
    print(answer)


if __name__ == "__main__":
    main()
